"""fix groceries id identity

Revision ID: 61a429e01a31
Revises: ee78daeaf1cf
Create Date: 2026-03-26 17:09:34.461186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a429e01a31'
down_revision: Union[str, Sequence[str], None] = 'ee78daeaf1cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade():
    op.execute("""
        ALTER TABLE groceries
        ALTER COLUMN id
        ADD GENERATED BY DEFAULT AS IDENTITY
    """)

def downgrade():
    op.execute("""
        ALTER TABLE groceries
        ALTER COLUMN id
        DROP IDENTITY IF EXISTS
    """)