"""add grocery unique constraint

Revision ID: ee78daeaf1cf
Revises: 91ae7b6fd675
Create Date: 2026-03-26 16:47:36.678257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee78daeaf1cf'
down_revision: Union[str, Sequence[str], None] = '91ae7b6fd675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groceries', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('groceries', sa.Column('name', sa.String(), nullable=False))
    op.add_column('groceries', sa.Column('measure', sa.String(), nullable=True))
    op.add_column('groceries', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_groceries_id'), 'groceries', ['id'], unique=False)
    op.create_unique_constraint('uq_grocery_user_name_measure', 'groceries', ['user_id', 'name', 'measure'])
    op.create_foreign_key(None, 'groceries', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'groceries', type_='foreignkey')
    op.drop_constraint('uq_grocery_user_name_measure', 'groceries', type_='unique')
    op.drop_index(op.f('ix_groceries_id'), table_name='groceries')
    op.drop_column('groceries', 'user_id')
    op.drop_column('groceries', 'measure')
    op.drop_column('groceries', 'name')
    op.drop_column('groceries', 'id')
    # ### end Alembic commands ###
